package com.modernkey.keyboard.emoji

data class EmojiItem(
    val emoji: String,
    val name: String,
    val keywords: List<String>,
    val category: EmojiCategory
)

object EmojiDataSource {

    val allEmojis: List<EmojiItem> by lazy { buildEmojiList() }

    private fun buildEmojiList(): List<EmojiItem> = listOf(
        // Smileys & Emotion
        EmojiItem("😀","grinning face", listOf("happy","smile","grin"), EmojiCategory.SMILEYS),
        EmojiItem("😃","grinning face big eyes", listOf("happy","smile"), EmojiCategory.SMILEYS),
        EmojiItem("😄","grinning face smiling eyes", listOf("happy","smile","laugh"), EmojiCategory.SMILEYS),
        EmojiItem("😁","beaming face smiling eyes", listOf("grin","happy"), EmojiCategory.SMILEYS),
        EmojiItem("😆","grinning squinting face", listOf("laugh","happy","lol"), EmojiCategory.SMILEYS),
        EmojiItem("😅","grinning face sweat", listOf("sweat","relief","nervous"), EmojiCategory.SMILEYS),
        EmojiItem("🤣","rolling on floor laughing", listOf("rofl","lol","laugh"), EmojiCategory.SMILEYS),
        EmojiItem("😂","face tears of joy", listOf("lol","cry","laugh"), EmojiCategory.SMILEYS),
        EmojiItem("🙂","slightly smiling face", listOf("smile","happy"), EmojiCategory.SMILEYS),
        EmojiItem("🙃","upside down face", listOf("silly","sarcasm","flip"), EmojiCategory.SMILEYS),
        EmojiItem("😉","winking face", listOf("wink","flirt"), EmojiCategory.SMILEYS),
        EmojiItem("😊","smiling face smiling eyes", listOf("blush","happy","smile"), EmojiCategory.SMILEYS),
        EmojiItem("😇","smiling face halo", listOf("angel","halo","good"), EmojiCategory.SMILEYS),
        EmojiItem("🥰","smiling face hearts", listOf("love","hearts","adore"), EmojiCategory.SMILEYS),
        EmojiItem("😍","smiling face heart eyes", listOf("love","heart eyes","adore"), EmojiCategory.SMILEYS),
        EmojiItem("🤩","star struck", listOf("wow","amazing","star","eyes"), EmojiCategory.SMILEYS),
        EmojiItem("😘","face blowing kiss", listOf("kiss","love","mwah"), EmojiCategory.SMILEYS),
        EmojiItem("😗","kissing face", listOf("kiss","love"), EmojiCategory.SMILEYS),
        EmojiItem("😚","kissing face closed eyes", listOf("kiss","love"), EmojiCategory.SMILEYS),
        EmojiItem("😙","kissing face smiling eyes", listOf("kiss","love"), EmojiCategory.SMILEYS),
        EmojiItem("🥲","smiling face tear", listOf("happy cry","grateful"), EmojiCategory.SMILEYS),
        EmojiItem("😋","face savoring food", listOf("yum","delicious","food"), EmojiCategory.SMILEYS),
        EmojiItem("😛","face tongue", listOf("tongue","playful"), EmojiCategory.SMILEYS),
        EmojiItem("😜","winking face tongue", listOf("wink","tongue","playful"), EmojiCategory.SMILEYS),
        EmojiItem("🤪","zany face", listOf("crazy","wild","silly"), EmojiCategory.SMILEYS),
        EmojiItem("😝","squinting face tongue", listOf("tongue","tease"), EmojiCategory.SMILEYS),
        EmojiItem("🤑","money mouth face", listOf("money","rich","dollar"), EmojiCategory.SMILEYS),
        EmojiItem("🤗","smiling face open hands", listOf("hug","warm","welcome"), EmojiCategory.SMILEYS),
        EmojiItem("🤭","face hand over mouth", listOf("secret","quiet","shh"), EmojiCategory.SMILEYS),
        EmojiItem("🤫","shushing face", listOf("quiet","shh","secret"), EmojiCategory.SMILEYS),
        EmojiItem("🤔","thinking face", listOf("think","hmm","ponder"), EmojiCategory.SMILEYS),
        EmojiItem("🤐","zipper mouth face", listOf("quiet","zip","secret"), EmojiCategory.SMILEYS),
        EmojiItem("🤨","face raised eyebrow", listOf("skeptical","dubious","suspicious"), EmojiCategory.SMILEYS),
        EmojiItem("😐","neutral face", listOf("neutral","meh","blank"), EmojiCategory.SMILEYS),
        EmojiItem("😑","expressionless face", listOf("blank","expressionless","dead"), EmojiCategory.SMILEYS),
        EmojiItem("😶","face without mouth", listOf("quiet","silent","speechless"), EmojiCategory.SMILEYS),
        EmojiItem("😏","smirking face", listOf("smirk","smug","sly"), EmojiCategory.SMILEYS),
        EmojiItem("😒","unamused face", listOf("unamused","bored","meh"), EmojiCategory.SMILEYS),
        EmojiItem("🙄","face rolling eyes", listOf("eye roll","whatever","ugh"), EmojiCategory.SMILEYS),
        EmojiItem("😬","grimacing face", listOf("grimace","awkward","oops"), EmojiCategory.SMILEYS),
        EmojiItem("😮","face open mouth", listOf("surprise","shock","wow"), EmojiCategory.SMILEYS),
        EmojiItem("😯","hushed face", listOf("shocked","silence","hush"), EmojiCategory.SMILEYS),
        EmojiItem("😲","astonished face", listOf("shock","wow","astonished"), EmojiCategory.SMILEYS),
        EmojiItem("😳","flushed face", listOf("blush","embarrass","shock"), EmojiCategory.SMILEYS),
        EmojiItem("🥺","pleading face", listOf("puppy eyes","please","beg"), EmojiCategory.SMILEYS),
        EmojiItem("😦","frowning face open mouth", listOf("frown","sad"), EmojiCategory.SMILEYS),
        EmojiItem("😧","anguished face", listOf("anguish","sad","pain"), EmojiCategory.SMILEYS),
        EmojiItem("😨","fearful face", listOf("fear","scared","afraid"), EmojiCategory.SMILEYS),
        EmojiItem("😰","anxious face sweat", listOf("nervous","anxious","sweat"), EmojiCategory.SMILEYS),
        EmojiItem("😥","sad relieved face", listOf("sad","relieved","phew"), EmojiCategory.SMILEYS),
        EmojiItem("😢","crying face", listOf("cry","sad","tear"), EmojiCategory.SMILEYS),
        EmojiItem("😭","loudly crying face", listOf("cry","sob","sad"), EmojiCategory.SMILEYS),
        EmojiItem("😱","face screaming in fear", listOf("scream","fear","scared"), EmojiCategory.SMILEYS),
        EmojiItem("😖","confounded face", listOf("confounded","confused","sad"), EmojiCategory.SMILEYS),
        EmojiItem("😣","persevering face", listOf("persevere","struggle"), EmojiCategory.SMILEYS),
        EmojiItem("😞","disappointed face", listOf("disappoint","sad","letdown"), EmojiCategory.SMILEYS),
        EmojiItem("😓","downcast face sweat", listOf("sad","sweat","hard work"), EmojiCategory.SMILEYS),
        EmojiItem("😩","weary face", listOf("tired","weary","exhausted"), EmojiCategory.SMILEYS),
        EmojiItem("😫","tired face", listOf("tired","exhausted"), EmojiCategory.SMILEYS),
        EmojiItem("🥱","yawning face", listOf("yawn","bored","tired"), EmojiCategory.SMILEYS),
        EmojiItem("😤","face steam from nose", listOf("triumph","frustrated","anger"), EmojiCategory.SMILEYS),
        EmojiItem("😡","enraged face", listOf("angry","mad","rage"), EmojiCategory.SMILEYS),
        EmojiItem("😠","angry face", listOf("angry","mad","grumpy"), EmojiCategory.SMILEYS),
        EmojiItem("🤬","face symbols on mouth", listOf("swear","cursing","angry"), EmojiCategory.SMILEYS),
        EmojiItem("😈","smiling face with horns", listOf("devil","evil","mischief"), EmojiCategory.SMILEYS),
        EmojiItem("👿","angry face with horns", listOf("devil","evil","demon"), EmojiCategory.SMILEYS),
        EmojiItem("💀","skull", listOf("skull","dead","death"), EmojiCategory.SMILEYS),
        EmojiItem("☠️","skull crossbones", listOf("skull","danger","pirate"), EmojiCategory.SMILEYS),
        EmojiItem("💩","pile of poo", listOf("poop","poo","crap"), EmojiCategory.SMILEYS),
        EmojiItem("🤡","clown face", listOf("clown","circus","funny"), EmojiCategory.SMILEYS),
        EmojiItem("👹","ogre", listOf("monster","ogre","japanese"), EmojiCategory.SMILEYS),
        EmojiItem("👺","goblin", listOf("goblin","monster","japanese"), EmojiCategory.SMILEYS),
        EmojiItem("👻","ghost", listOf("ghost","halloween","spooky"), EmojiCategory.SMILEYS),
        EmojiItem("👽","alien", listOf("alien","extraterrestrial","ufo"), EmojiCategory.SMILEYS),
        EmojiItem("👾","alien monster", listOf("alien","monster","game"), EmojiCategory.SMILEYS),
        EmojiItem("🤖","robot", listOf("robot","bot","machine"), EmojiCategory.SMILEYS),

        // People & Body
        EmojiItem("👋","waving hand", listOf("wave","hi","hello","bye"), EmojiCategory.PEOPLE),
        EmojiItem("🤚","raised back of hand", listOf("hand","raise","stop"), EmojiCategory.PEOPLE),
        EmojiItem("🖐️","hand fingers splayed", listOf("hand","five","splayed"), EmojiCategory.PEOPLE),
        EmojiItem("✋","raised hand", listOf("hand","stop","high five"), EmojiCategory.PEOPLE),
        EmojiItem("🖖","vulcan salute", listOf("spock","star trek","live long"), EmojiCategory.PEOPLE),
        EmojiItem("👌","ok hand", listOf("ok","okay","perfect"), EmojiCategory.PEOPLE),
        EmojiItem("🤌","pinched fingers", listOf("italian","pinch","gesture"), EmojiCategory.PEOPLE),
        EmojiItem("✌️","victory hand", listOf("peace","victory","two"), EmojiCategory.PEOPLE),
        EmojiItem("🤞","crossed fingers", listOf("luck","fingers crossed","hope"), EmojiCategory.PEOPLE),
        EmojiItem("🤟","love you gesture", listOf("love","rock","hand"), EmojiCategory.PEOPLE),
        EmojiItem("🤘","sign of horns", listOf("rock","metal","horns"), EmojiCategory.PEOPLE),
        EmojiItem("🤙","call me hand", listOf("call","phone","hang loose"), EmojiCategory.PEOPLE),
        EmojiItem("👈","backhand index pointing left", listOf("left","point","direction"), EmojiCategory.PEOPLE),
        EmojiItem("👉","backhand index pointing right", listOf("right","point","direction"), EmojiCategory.PEOPLE),
        EmojiItem("👆","backhand index pointing up", listOf("up","point","above"), EmojiCategory.PEOPLE),
        EmojiItem("🖕","middle finger", listOf("middle","rude","flip off"), EmojiCategory.PEOPLE),
        EmojiItem("👇","backhand index pointing down", listOf("down","point","below"), EmojiCategory.PEOPLE),
        EmojiItem("☝️","index pointing up", listOf("up","one","point"), EmojiCategory.PEOPLE),
        EmojiItem("👍","thumbs up", listOf("like","thumbs up","good","approve"), EmojiCategory.PEOPLE),
        EmojiItem("👎","thumbs down", listOf("dislike","thumbs down","bad"), EmojiCategory.PEOPLE),
        EmojiItem("✊","raised fist", listOf("fist","power","solidarity"), EmojiCategory.PEOPLE),
        EmojiItem("👊","oncoming fist", listOf("fist","punch","bump"), EmojiCategory.PEOPLE),
        EmojiItem("🤛","left facing fist", listOf("fist","left","bump"), EmojiCategory.PEOPLE),
        EmojiItem("🤜","right facing fist", listOf("fist","right","bump"), EmojiCategory.PEOPLE),
        EmojiItem("👏","clapping hands", listOf("clap","applause","congratulations"), EmojiCategory.PEOPLE),
        EmojiItem("🙌","raising hands", listOf("hooray","raised hands","celebrate"), EmojiCategory.PEOPLE),
        EmojiItem("👐","open hands", listOf("open","hug","jazz hands"), EmojiCategory.PEOPLE),
        EmojiItem("🤲","palms up together", listOf("prayer","hands","cup"), EmojiCategory.PEOPLE),
        EmojiItem("🤝","handshake", listOf("deal","shake","agreement","hello"), EmojiCategory.PEOPLE),
        EmojiItem("🙏","folded hands", listOf("pray","please","thanks","namaste"), EmojiCategory.PEOPLE),
        EmojiItem("💪","flexed biceps", listOf("muscle","strong","flex","gym"), EmojiCategory.PEOPLE),
        EmojiItem("🦾","mechanical arm", listOf("bionic","cyborg","prosthetic"), EmojiCategory.PEOPLE),
        EmojiItem("🦿","mechanical leg", listOf("bionic","cyborg","prosthetic"), EmojiCategory.PEOPLE),
        EmojiItem("🦵","leg", listOf("leg","kick","limb"), EmojiCategory.PEOPLE),
        EmojiItem("🦶","foot", listOf("foot","kick","stomp"), EmojiCategory.PEOPLE),
        EmojiItem("👂","ear", listOf("ear","listen","hear"), EmojiCategory.PEOPLE),
        EmojiItem("👃","nose", listOf("nose","smell"), EmojiCategory.PEOPLE),
        EmojiItem("🧠","brain", listOf("brain","mind","think","smart"), EmojiCategory.PEOPLE),
        EmojiItem("🦷","tooth", listOf("tooth","dentist"), EmojiCategory.PEOPLE),
        EmojiItem("🦴","bone", listOf("bone","skeleton"), EmojiCategory.PEOPLE),
        EmojiItem("👀","eyes", listOf("eyes","look","see","watch"), EmojiCategory.PEOPLE),
        EmojiItem("👁️","eye", listOf("eye","look","see"), EmojiCategory.PEOPLE),
        EmojiItem("👅","tongue", listOf("tongue","taste"), EmojiCategory.PEOPLE),
        EmojiItem("👄","mouth", listOf("mouth","lips","kiss"), EmojiCategory.PEOPLE),

        // Animals & Nature
        EmojiItem("🐶","dog face", listOf("dog","puppy","pet","woof"), EmojiCategory.ANIMALS),
        EmojiItem("🐱","cat face", listOf("cat","kitten","pet","meow"), EmojiCategory.ANIMALS),
        EmojiItem("🐭","mouse face", listOf("mouse","rodent"), EmojiCategory.ANIMALS),
        EmojiItem("🐹","hamster", listOf("hamster","pet","rodent"), EmojiCategory.ANIMALS),
        EmojiItem("🐰","rabbit face", listOf("rabbit","bunny","easter"), EmojiCategory.ANIMALS),
        EmojiItem("🦊","fox", listOf("fox","foxy"), EmojiCategory.ANIMALS),
        EmojiItem("🐻","bear", listOf("bear","teddy"), EmojiCategory.ANIMALS),
        EmojiItem("🐼","panda", listOf("panda","bear","china"), EmojiCategory.ANIMALS),
        EmojiItem("🐨","koala", listOf("koala","bear","australia"), EmojiCategory.ANIMALS),
        EmojiItem("🐯","tiger face", listOf("tiger","wild","cat"), EmojiCategory.ANIMALS),
        EmojiItem("🦁","lion", listOf("lion","king","wild"), EmojiCategory.ANIMALS),
        EmojiItem("🐮","cow face", listOf("cow","moo","farm"), EmojiCategory.ANIMALS),
        EmojiItem("🐷","pig face", listOf("pig","oink","farm"), EmojiCategory.ANIMALS),
        EmojiItem("🐸","frog", listOf("frog","kermit"), EmojiCategory.ANIMALS),
        EmojiItem("🐵","monkey face", listOf("monkey","ape","banana"), EmojiCategory.ANIMALS),
        EmojiItem("🙈","see no evil monkey", listOf("monkey","see no evil","blind"), EmojiCategory.ANIMALS),
        EmojiItem("🙉","hear no evil monkey", listOf("monkey","hear no evil"), EmojiCategory.ANIMALS),
        EmojiItem("🙊","speak no evil monkey", listOf("monkey","speak no evil","quiet"), EmojiCategory.ANIMALS),
        EmojiItem("🐔","chicken", listOf("chicken","hen","bird","farm"), EmojiCategory.ANIMALS),
        EmojiItem("🐧","penguin", listOf("penguin","bird","cold"), EmojiCategory.ANIMALS),
        EmojiItem("🐦","bird", listOf("bird","tweet","fly"), EmojiCategory.ANIMALS),
        EmojiItem("🦅","eagle", listOf("eagle","bird","freedom"), EmojiCategory.ANIMALS),
        EmojiItem("🦆","duck", listOf("duck","quack","bird"), EmojiCategory.ANIMALS),
        EmojiItem("🦉","owl", listOf("owl","wise","bird","night"), EmojiCategory.ANIMALS),
        EmojiItem("🦇","bat", listOf("bat","vampire","halloween","night"), EmojiCategory.ANIMALS),
        EmojiItem("🐺","wolf", listOf("wolf","howl","wild"), EmojiCategory.ANIMALS),
        EmojiItem("🐗","boar", listOf("boar","pig","wild"), EmojiCategory.ANIMALS),
        EmojiItem("🐴","horse face", listOf("horse","neigh","pony"), EmojiCategory.ANIMALS),
        EmojiItem("🦄","unicorn", listOf("unicorn","magic","rainbow","mythical"), EmojiCategory.ANIMALS),
        EmojiItem("🐝","honeybee", listOf("bee","honey","insect"), EmojiCategory.ANIMALS),
        EmojiItem("🐛","bug", listOf("bug","caterpillar","insect"), EmojiCategory.ANIMALS),
        EmojiItem("🦋","butterfly", listOf("butterfly","insect","beautiful","transform"), EmojiCategory.ANIMALS),
        EmojiItem("🐌","snail", listOf("snail","slow","shell"), EmojiCategory.ANIMALS),
        EmojiItem("🐍","snake", listOf("snake","serpent","hiss"), EmojiCategory.ANIMALS),
        EmojiItem("🦎","lizard", listOf("lizard","reptile"), EmojiCategory.ANIMALS),
        EmojiItem("🐢","turtle", listOf("turtle","tortoise","slow"), EmojiCategory.ANIMALS),
        EmojiItem("🦖","t rex", listOf("dinosaur","t-rex","jurassic","extinct"), EmojiCategory.ANIMALS),
        EmojiItem("🦕","sauropod", listOf("dinosaur","brontosaurus","extinct"), EmojiCategory.ANIMALS),
        EmojiItem("🐊","crocodile", listOf("crocodile","alligator","reptile"), EmojiCategory.ANIMALS),
        EmojiItem("🐋","whale", listOf("whale","ocean","big"), EmojiCategory.ANIMALS),
        EmojiItem("🐬","dolphin", listOf("dolphin","ocean","smart"), EmojiCategory.ANIMALS),
        EmojiItem("🦈","shark", listOf("shark","ocean","danger"), EmojiCategory.ANIMALS),
        EmojiItem("🐙","octopus", listOf("octopus","tentacle","ocean"), EmojiCategory.ANIMALS),
        EmojiItem("🦑","squid", listOf("squid","tentacle","ocean"), EmojiCategory.ANIMALS),
        EmojiItem("🦐","shrimp", listOf("shrimp","prawn","seafood"), EmojiCategory.ANIMALS),
        EmojiItem("🦀","crab", listOf("crab","seafood","sideways"), EmojiCategory.ANIMALS),
        EmojiItem("🌸","cherry blossom", listOf("flower","sakura","spring","pink"), EmojiCategory.ANIMALS),
        EmojiItem("🌺","hibiscus", listOf("flower","hibiscus","tropical"), EmojiCategory.ANIMALS),
        EmojiItem("🌻","sunflower", listOf("sunflower","flower","sun","yellow"), EmojiCategory.ANIMALS),
        EmojiItem("🌹","rose", listOf("rose","flower","love","red"), EmojiCategory.ANIMALS),
        EmojiItem("🌷","tulip", listOf("tulip","flower","spring"), EmojiCategory.ANIMALS),
        EmojiItem("🌱","seedling", listOf("seedling","plant","growth","nature"), EmojiCategory.ANIMALS),
        EmojiItem("🌿","herb", listOf("herb","plant","green","nature"), EmojiCategory.ANIMALS),
        EmojiItem("🍀","four leaf clover", listOf("clover","luck","lucky","green"), EmojiCategory.ANIMALS),
        EmojiItem("🎋","tanabata tree", listOf("bamboo","japanese"), EmojiCategory.ANIMALS),
        EmojiItem("🍁","maple leaf", listOf("maple","leaf","fall","autumn","canada"), EmojiCategory.ANIMALS),
        EmojiItem("🍂","fallen leaf", listOf("leaf","fall","autumn"), EmojiCategory.ANIMALS),
        EmojiItem("🍃","leaf fluttering", listOf("leaf","wind","nature"), EmojiCategory.ANIMALS),
        EmojiItem("🌊","water wave", listOf("wave","ocean","water","surf"), EmojiCategory.ANIMALS),
        EmojiItem("🌈","rainbow", listOf("rainbow","colorful","gay","pride","weather"), EmojiCategory.ANIMALS),
        EmojiItem("⭐","star", listOf("star","night","sky","favorite"), EmojiCategory.ANIMALS),
        EmojiItem("🌙","crescent moon", listOf("moon","night","sleep","crescent"), EmojiCategory.ANIMALS),
        EmojiItem("☀️","sun", listOf("sun","bright","day","summer"), EmojiCategory.ANIMALS),
        EmojiItem("❄️","snowflake", listOf("snow","cold","winter","ice","frozen"), EmojiCategory.ANIMALS),
        EmojiItem("🔥","fire", listOf("fire","hot","flame","burn","lit"), EmojiCategory.ANIMALS),
        EmojiItem("💧","droplet", listOf("water","drop","blue","cry"), EmojiCategory.ANIMALS),
        EmojiItem("🌍","earth africa", listOf("earth","world","globe","africa"), EmojiCategory.ANIMALS),
        EmojiItem("🌎","earth americas", listOf("earth","world","globe","americas"), EmojiCategory.ANIMALS),
        EmojiItem("🌏","earth asia", listOf("earth","world","globe","asia"), EmojiCategory.ANIMALS),

        // Food & Drink
        EmojiItem("🍎","red apple", listOf("apple","fruit","red"), EmojiCategory.FOOD),
        EmojiItem("🍊","tangerine", listOf("orange","fruit","citrus"), EmojiCategory.FOOD),
        EmojiItem("🍋","lemon", listOf("lemon","fruit","citrus","sour","yellow"), EmojiCategory.FOOD),
        EmojiItem("🍇","grapes", listOf("grapes","fruit","wine","purple"), EmojiCategory.FOOD),
        EmojiItem("🍓","strawberry", listOf("strawberry","fruit","red"), EmojiCategory.FOOD),
        EmojiItem("🍑","peach", listOf("peach","fruit","butt"), EmojiCategory.FOOD),
        EmojiItem("🍒","cherries", listOf("cherries","fruit","red"), EmojiCategory.FOOD),
        EmojiItem("🍍","pineapple", listOf("pineapple","fruit","tropical"), EmojiCategory.FOOD),
        EmojiItem("🥭","mango", listOf("mango","fruit","tropical"), EmojiCategory.FOOD),
        EmojiItem("🍌","banana", listOf("banana","fruit","yellow"), EmojiCategory.FOOD),
        EmojiItem("🍉","watermelon", listOf("watermelon","fruit","summer"), EmojiCategory.FOOD),
        EmojiItem("🍕","pizza", listOf("pizza","food","italian","cheese"), EmojiCategory.FOOD),
        EmojiItem("🍔","hamburger", listOf("burger","hamburger","food","fast food"), EmojiCategory.FOOD),
        EmojiItem("🍟","french fries", listOf("fries","chips","fast food"), EmojiCategory.FOOD),
        EmojiItem("🌮","taco", listOf("taco","mexican","food"), EmojiCategory.FOOD),
        EmojiItem("🌯","burrito", listOf("burrito","wrap","mexican","food"), EmojiCategory.FOOD),
        EmojiItem("🍜","steaming bowl", listOf("noodles","ramen","soup","food"), EmojiCategory.FOOD),
        EmojiItem("🍣","sushi", listOf("sushi","japanese","fish","food"), EmojiCategory.FOOD),
        EmojiItem("🍱","bento box", listOf("bento","japanese","lunch","box"), EmojiCategory.FOOD),
        EmojiItem("🍛","curry rice", listOf("curry","rice","indian","food"), EmojiCategory.FOOD),
        EmojiItem("🍰","shortcake", listOf("cake","dessert","birthday","sweet"), EmojiCategory.FOOD),
        EmojiItem("🎂","birthday cake", listOf("cake","birthday","celebrate"), EmojiCategory.FOOD),
        EmojiItem("🍩","doughnut", listOf("donut","doughnut","dessert","sweet"), EmojiCategory.FOOD),
        EmojiItem("🍪","cookie", listOf("cookie","biscuit","dessert","sweet"), EmojiCategory.FOOD),
        EmojiItem("🍫","chocolate bar", listOf("chocolate","candy","sweet"), EmojiCategory.FOOD),
        EmojiItem("🍬","candy", listOf("candy","sweet","sugar"), EmojiCategory.FOOD),
        EmojiItem("🍭","lollipop", listOf("lollipop","candy","sweet"), EmojiCategory.FOOD),
        EmojiItem("☕","hot beverage", listOf("coffee","tea","hot","drink","cup"), EmojiCategory.FOOD),
        EmojiItem("🍵","teacup without handle", listOf("tea","green tea","hot","drink"), EmojiCategory.FOOD),
        EmojiItem("🧋","bubble tea", listOf("boba","bubble tea","milk tea","drink"), EmojiCategory.FOOD),
        EmojiItem("🥤","cup with straw", listOf("drink","soda","juice","cup"), EmojiCategory.FOOD),
        EmojiItem("🍺","beer mug", listOf("beer","drink","pub","cheers"), EmojiCategory.FOOD),
        EmojiItem("🍻","clinking beer mugs", listOf("beer","cheers","toast","party"), EmojiCategory.FOOD),
        EmojiItem("🥂","clinking glasses", listOf("champagne","toast","cheers","celebrate"), EmojiCategory.FOOD),
        EmojiItem("🍷","wine glass", listOf("wine","drink","red wine"), EmojiCategory.FOOD),

        // Travel & Places
        EmojiItem("✈️","airplane", listOf("airplane","fly","travel","flight"), EmojiCategory.TRAVEL),
        EmojiItem("🚀","rocket", listOf("rocket","space","launch","fast"), EmojiCategory.TRAVEL),
        EmojiItem("🏖️","beach with umbrella", listOf("beach","vacation","summer","ocean"), EmojiCategory.TRAVEL),
        EmojiItem("🏔️","snow capped mountain", listOf("mountain","snow","peak","nature"), EmojiCategory.TRAVEL),
        EmojiItem("🗼","tokyo tower", listOf("tokyo","tower","japan"), EmojiCategory.TRAVEL),
        EmojiItem("🗽","statue of liberty", listOf("liberty","usa","new york","freedom"), EmojiCategory.TRAVEL),
        EmojiItem("🏰","european castle", listOf("castle","fairytale","medieval"), EmojiCategory.TRAVEL),
        EmojiItem("🌆","cityscape at dusk", listOf("city","dusk","sunset","urban"), EmojiCategory.TRAVEL),
        EmojiItem("🚗","automobile", listOf("car","drive","vehicle","red car"), EmojiCategory.TRAVEL),
        EmojiItem("🚕","taxi", listOf("taxi","cab","yellow","transport"), EmojiCategory.TRAVEL),
        EmojiItem("🚌","bus", listOf("bus","transport","vehicle"), EmojiCategory.TRAVEL),
        EmojiItem("🚂","locomotive", listOf("train","locomotive","steam"), EmojiCategory.TRAVEL),
        EmojiItem("🚢","ship", listOf("ship","cruise","boat","ocean"), EmojiCategory.TRAVEL),
        EmojiItem("🛵","motor scooter", listOf("scooter","moped","ride"), EmojiCategory.TRAVEL),
        EmojiItem("🚲","bicycle", listOf("bicycle","bike","cycling"), EmojiCategory.TRAVEL),
        EmojiItem("🛸","flying saucer", listOf("ufo","alien","flying saucer","space"), EmojiCategory.TRAVEL),
        EmojiItem("⛵","sailboat", listOf("sailboat","sail","boat","ocean"), EmojiCategory.TRAVEL),
        EmojiItem("🗺️","world map", listOf("map","world","travel","navigate"), EmojiCategory.TRAVEL),
        EmojiItem("🧭","compass", listOf("compass","direction","navigate"), EmojiCategory.TRAVEL),
        EmojiItem("🏕️","camping", listOf("camping","tent","nature","outdoor"), EmojiCategory.TRAVEL),
        EmojiItem("🏝️","desert island", listOf("island","tropical","palm tree"), EmojiCategory.TRAVEL),

        // Activities
        EmojiItem("⚽","soccer ball", listOf("soccer","football","ball","sport"), EmojiCategory.ACTIVITIES),
        EmojiItem("🏀","basketball", listOf("basketball","ball","sport","nba"), EmojiCategory.ACTIVITIES),
        EmojiItem("🏈","american football", listOf("football","nfl","american","sport"), EmojiCategory.ACTIVITIES),
        EmojiItem("⚾","baseball", listOf("baseball","ball","mlb","sport"), EmojiCategory.ACTIVITIES),
        EmojiItem("🎾","tennis", listOf("tennis","ball","sport","racket"), EmojiCategory.ACTIVITIES),
        EmojiItem("🏐","volleyball", listOf("volleyball","ball","sport","net"), EmojiCategory.ACTIVITIES),
        EmojiItem("🏉","rugby football", listOf("rugby","ball","sport"), EmojiCategory.ACTIVITIES),
        EmojiItem("🎱","pool 8 ball", listOf("billiards","pool","8 ball","game"), EmojiCategory.ACTIVITIES),
        EmojiItem("🏓","ping pong", listOf("ping pong","table tennis","paddle","sport"), EmojiCategory.ACTIVITIES),
        EmojiItem("🥊","boxing glove", listOf("boxing","fight","punch","sport"), EmojiCategory.ACTIVITIES),
        EmojiItem("🎮","video game", listOf("game","controller","gaming","play"), EmojiCategory.ACTIVITIES),
        EmojiItem("🎲","game die", listOf("dice","die","game","luck","random"), EmojiCategory.ACTIVITIES),
        EmojiItem("🎯","direct hit", listOf("target","bullseye","dart","aim"), EmojiCategory.ACTIVITIES),
        EmojiItem("🎭","performing arts", listOf("theater","drama","masks","performance"), EmojiCategory.ACTIVITIES),
        EmojiItem("🎨","artist palette", listOf("art","paint","artist","creative"), EmojiCategory.ACTIVITIES),
        EmojiItem("🎪","circus tent", listOf("circus","tent","entertainment"), EmojiCategory.ACTIVITIES),
        EmojiItem("🎬","clapper board", listOf("movie","film","action","cinema"), EmojiCategory.ACTIVITIES),
        EmojiItem("🎤","microphone", listOf("microphone","sing","karaoke","performance"), EmojiCategory.ACTIVITIES),
        EmojiItem("🎵","musical note", listOf("music","note","sound","song"), EmojiCategory.ACTIVITIES),
        EmojiItem("🎶","musical notes", listOf("music","notes","sound","song"), EmojiCategory.ACTIVITIES),
        EmojiItem("🎸","guitar", listOf("guitar","music","rock","instrument"), EmojiCategory.ACTIVITIES),
        EmojiItem("🥇","1st place medal", listOf("gold","medal","first","winner","trophy"), EmojiCategory.ACTIVITIES),
        EmojiItem("🏆","trophy", listOf("trophy","winner","award","champion","cup"), EmojiCategory.ACTIVITIES),
        EmojiItem("🥳","partying face", listOf("party","celebrate","birthday","fun"), EmojiCategory.ACTIVITIES),
        EmojiItem("🎉","party popper", listOf("party","celebrate","confetti","tada"), EmojiCategory.ACTIVITIES),
        EmojiItem("🎊","confetti ball", listOf("party","celebrate","confetti"), EmojiCategory.ACTIVITIES),
        EmojiItem("🎁","wrapped gift", listOf("gift","present","box","birthday","christmas"), EmojiCategory.ACTIVITIES),

        // Objects
        EmojiItem("💡","light bulb", listOf("idea","bulb","light","think"), EmojiCategory.OBJECTS),
        EmojiItem("💻","laptop", listOf("laptop","computer","screen","work"), EmojiCategory.OBJECTS),
        EmojiItem("🖥️","desktop computer", listOf("desktop","computer","monitor","screen"), EmojiCategory.OBJECTS),
        EmojiItem("📱","mobile phone", listOf("phone","mobile","cell","smartphone"), EmojiCategory.OBJECTS),
        EmojiItem("⌨️","keyboard", listOf("keyboard","type","computer"), EmojiCategory.OBJECTS),
        EmojiItem("🖨️","printer", listOf("printer","print","computer"), EmojiCategory.OBJECTS),
        EmojiItem("📷","camera", listOf("camera","photo","picture","photography"), EmojiCategory.OBJECTS),
        EmojiItem("📸","camera with flash", listOf("camera","flash","photo","selfie"), EmojiCategory.OBJECTS),
        EmojiItem("📹","video camera", listOf("video","camera","film","record"), EmojiCategory.OBJECTS),
        EmojiItem("📺","television", listOf("tv","television","watch","screen"), EmojiCategory.OBJECTS),
        EmojiItem("📻","radio", listOf("radio","music","broadcast"), EmojiCategory.OBJECTS),
        EmojiItem("🔋","battery", listOf("battery","power","energy","charge"), EmojiCategory.OBJECTS),
        EmojiItem("🔌","electric plug", listOf("plug","power","electric","charge"), EmojiCategory.OBJECTS),
        EmojiItem("💾","floppy disk", listOf("floppy","disk","save","data","storage"), EmojiCategory.OBJECTS),
        EmojiItem("📀","dvd", listOf("dvd","disc","disk","cd"), EmojiCategory.OBJECTS),
        EmojiItem("📚","books", listOf("books","library","read","education","knowledge"), EmojiCategory.OBJECTS),
        EmojiItem("📖","open book", listOf("book","read","open","education"), EmojiCategory.OBJECTS),
        EmojiItem("📝","memo", listOf("memo","note","write","pen","list"), EmojiCategory.OBJECTS),
        EmojiItem("✏️","pencil", listOf("pencil","write","draw","edit"), EmojiCategory.OBJECTS),
        EmojiItem("🖊️","pen", listOf("pen","write","ink","sign"), EmojiCategory.OBJECTS),
        EmojiItem("📌","pushpin", listOf("pin","pushpin","location","mark"), EmojiCategory.OBJECTS),
        EmojiItem("📎","paperclip", listOf("paperclip","attach","clip"), EmojiCategory.OBJECTS),
        EmojiItem("✂️","scissors", listOf("scissors","cut","craft"), EmojiCategory.OBJECTS),
        EmojiItem("🔒","locked", listOf("locked","lock","security","private"), EmojiCategory.OBJECTS),
        EmojiItem("🔓","unlocked", listOf("unlocked","lock","open","security"), EmojiCategory.OBJECTS),
        EmojiItem("🔑","key", listOf("key","unlock","password","access"), EmojiCategory.OBJECTS),
        EmojiItem("🔨","hammer", listOf("hammer","tool","build","fix"), EmojiCategory.OBJECTS),
        EmojiItem("⚙️","gear", listOf("gear","settings","cog","mechanism"), EmojiCategory.OBJECTS),
        EmojiItem("🔧","wrench", listOf("wrench","tool","fix","repair"), EmojiCategory.OBJECTS),
        EmojiItem("🧲","magnet", listOf("magnet","attract","pull"), EmojiCategory.OBJECTS),
        EmojiItem("💊","pill", listOf("pill","medicine","drug","medication"), EmojiCategory.OBJECTS),
        EmojiItem("🩺","stethoscope", listOf("doctor","stethoscope","medical","health"), EmojiCategory.OBJECTS),
        EmojiItem("🧪","test tube", listOf("science","experiment","chemistry","lab"), EmojiCategory.OBJECTS),
        EmojiItem("🔭","telescope", listOf("telescope","space","astronomy","look"), EmojiCategory.OBJECTS),
        EmojiItem("🔬","microscope", listOf("microscope","science","biology","lab"), EmojiCategory.OBJECTS),
        EmojiItem("💰","money bag", listOf("money","bag","rich","cash","dollar"), EmojiCategory.OBJECTS),
        EmojiItem("💵","dollar banknote", listOf("dollar","money","cash","usd"), EmojiCategory.OBJECTS),
        EmojiItem("💳","credit card", listOf("credit card","payment","card","money"), EmojiCategory.OBJECTS),

        // Symbols
        EmojiItem("❤️","red heart", listOf("heart","love","red","like"), EmojiCategory.SYMBOLS),
        EmojiItem("🧡","orange heart", listOf("heart","orange","love"), EmojiCategory.SYMBOLS),
        EmojiItem("💛","yellow heart", listOf("heart","yellow","love","happy"), EmojiCategory.SYMBOLS),
        EmojiItem("💚","green heart", listOf("heart","green","love","nature"), EmojiCategory.SYMBOLS),
        EmojiItem("💙","blue heart", listOf("heart","blue","love","trust"), EmojiCategory.SYMBOLS),
        EmojiItem("💜","purple heart", listOf("heart","purple","love"), EmojiCategory.SYMBOLS),
        EmojiItem("🖤","black heart", listOf("heart","black","love","dark"), EmojiCategory.SYMBOLS),
        EmojiItem("🤍","white heart", listOf("heart","white","love","pure"), EmojiCategory.SYMBOLS),
        EmojiItem("💔","broken heart", listOf("broken heart","heartbreak","sad"), EmojiCategory.SYMBOLS),
        EmojiItem("💕","two hearts", listOf("hearts","two","love"), EmojiCategory.SYMBOLS),
        EmojiItem("💞","revolving hearts", listOf("hearts","revolving","love"), EmojiCategory.SYMBOLS),
        EmojiItem("💓","beating heart", listOf("heart","beat","love","pulse"), EmojiCategory.SYMBOLS),
        EmojiItem("💗","growing heart", listOf("heart","growing","love","pink"), EmojiCategory.SYMBOLS),
        EmojiItem("💖","sparkling heart", listOf("heart","sparkle","love"), EmojiCategory.SYMBOLS),
        EmojiItem("💘","heart with arrow", listOf("heart","arrow","cupid","love"), EmojiCategory.SYMBOLS),
        EmojiItem("💝","heart with ribbon", listOf("heart","ribbon","gift","love"), EmojiCategory.SYMBOLS),
        EmojiItem("💟","heart decoration", listOf("heart","purple","decoration"), EmojiCategory.SYMBOLS),
        EmojiItem("☮️","peace symbol", listOf("peace","sign"), EmojiCategory.SYMBOLS),
        EmojiItem("✝️","latin cross", listOf("cross","christian","religion"), EmojiCategory.SYMBOLS),
        EmojiItem("☯️","yin yang", listOf("yin yang","balance","peace","tao"), EmojiCategory.SYMBOLS),
        EmojiItem("⚡","high voltage", listOf("lightning","bolt","electric","fast","power"), EmojiCategory.SYMBOLS),
        EmojiItem("💥","collision", listOf("boom","explosion","fire","bang"), EmojiCategory.SYMBOLS),
        EmojiItem("💫","dizzy", listOf("dizzy","stars","sparkle","spin"), EmojiCategory.SYMBOLS),
        EmojiItem("⭐","star", listOf("star","favorite","gold","shining"), EmojiCategory.SYMBOLS),
        EmojiItem("🌟","glowing star", listOf("star","glow","shine","bright"), EmojiCategory.SYMBOLS),
        EmojiItem("✨","sparkles", listOf("sparkles","magic","shine","glitter","stars"), EmojiCategory.SYMBOLS),
        EmojiItem("🎆","fireworks", listOf("fireworks","celebration","new year","boom"), EmojiCategory.SYMBOLS),
        EmojiItem("🎇","sparkler", listOf("sparkler","fireworks","celebration"), EmojiCategory.SYMBOLS),
        EmojiItem("🔴","red circle", listOf("red","circle","dot","stop"), EmojiCategory.SYMBOLS),
        EmojiItem("🟠","orange circle", listOf("orange","circle","dot"), EmojiCategory.SYMBOLS),
        EmojiItem("🟡","yellow circle", listOf("yellow","circle","dot"), EmojiCategory.SYMBOLS),
        EmojiItem("🟢","green circle", listOf("green","circle","dot","go"), EmojiCategory.SYMBOLS),
        EmojiItem("🔵","blue circle", listOf("blue","circle","dot"), EmojiCategory.SYMBOLS),
        EmojiItem("🟣","purple circle", listOf("purple","circle","dot"), EmojiCategory.SYMBOLS),
        EmojiItem("⚫","black circle", listOf("black","circle","dot"), EmojiCategory.SYMBOLS),
        EmojiItem("⚪","white circle", listOf("white","circle","dot"), EmojiCategory.SYMBOLS),
        EmojiItem("✅","check mark button", listOf("check","tick","correct","done","yes"), EmojiCategory.SYMBOLS),
        EmojiItem("❌","cross mark", listOf("cross","x","no","wrong","cancel"), EmojiCategory.SYMBOLS),
        EmojiItem("‼️","double exclamation mark", listOf("exclamation","important","!!"), EmojiCategory.SYMBOLS),
        EmojiItem("❓","question mark", listOf("question","?","huh","confused"), EmojiCategory.SYMBOLS),
        EmojiItem("💯","hundred points", listOf("100","perfect","score","hundred"), EmojiCategory.SYMBOLS),
        EmojiItem("🔝","top arrow", listOf("top","up","arrow"), EmojiCategory.SYMBOLS),
        EmojiItem("🆕","new button", listOf("new","label","button"), EmojiCategory.SYMBOLS),
        EmojiItem("🆗","ok button", listOf("ok","okay","button"), EmojiCategory.SYMBOLS),
        EmojiItem("🆙","up button", listOf("up","button","grade"), EmojiCategory.SYMBOLS),
        EmojiItem("🔃","clockwise arrows button", listOf("refresh","reload","sync","arrows"), EmojiCategory.SYMBOLS),
        EmojiItem("🔄","counterclockwise arrows button", listOf("refresh","reload","sync"), EmojiCategory.SYMBOLS),
        EmojiItem("📢","loudspeaker", listOf("announcement","loud","speaker","megaphone"), EmojiCategory.SYMBOLS),
        EmojiItem("🔔","bell", listOf("bell","ring","notification","alert"), EmojiCategory.SYMBOLS),
        EmojiItem("🔕","bell with slash", listOf("bell","mute","silent","no ring"), EmojiCategory.SYMBOLS),
        EmojiItem("🎵","musical note", listOf("music","note","sound"), EmojiCategory.SYMBOLS),
        EmojiItem("🎶","musical notes", listOf("music","notes","sound","song"), EmojiCategory.SYMBOLS),
        EmojiItem("📡","satellite antenna", listOf("satellite","antenna","signal","network"), EmojiCategory.SYMBOLS),
        EmojiItem("🚫","prohibited", listOf("no","ban","prohibited","not allowed","circle x"), EmojiCategory.SYMBOLS),
        EmojiItem("⚠️","warning", listOf("warning","caution","alert","danger"), EmojiCategory.SYMBOLS),
        EmojiItem("🔞","no one under eighteen", listOf("18+","adult","no","mature"), EmojiCategory.SYMBOLS),

        // Flags
        EmojiItem("🏳️","white flag", listOf("white","flag","surrender"), EmojiCategory.FLAGS),
        EmojiItem("🏴","black flag", listOf("black","flag","pirate"), EmojiCategory.FLAGS),
        EmojiItem("🚩","triangular flag", listOf("flag","red","triangle","warning"), EmojiCategory.FLAGS),
        EmojiItem("🏁","chequered flag", listOf("checkered","flag","race","finish"), EmojiCategory.FLAGS),
        EmojiItem("🏳️‍🌈","rainbow flag", listOf("rainbow","pride","lgbtq","gay","flag"), EmojiCategory.FLAGS),
        EmojiItem("🇧🇩","flag: Bangladesh", listOf("bangladesh","bd","flag","country"), EmojiCategory.FLAGS),
        EmojiItem("🇮🇳","flag: India", listOf("india","in","flag","country"), EmojiCategory.FLAGS),
        EmojiItem("🇺🇸","flag: United States", listOf("usa","us","united states","american","flag"), EmojiCategory.FLAGS),
        EmojiItem("🇬🇧","flag: United Kingdom", listOf("uk","britain","england","flag"), EmojiCategory.FLAGS),
        EmojiItem("🇨🇦","flag: Canada", listOf("canada","ca","maple","flag"), EmojiCategory.FLAGS),
        EmojiItem("🇦🇺","flag: Australia", listOf("australia","au","flag"), EmojiCategory.FLAGS),
        EmojiItem("🇩🇪","flag: Germany", listOf("germany","de","deutschland","flag"), EmojiCategory.FLAGS),
        EmojiItem("🇫🇷","flag: France", listOf("france","fr","french","flag"), EmojiCategory.FLAGS),
        EmojiItem("🇯🇵","flag: Japan", listOf("japan","jp","japanese","flag"), EmojiCategory.FLAGS),
        EmojiItem("🇨🇳","flag: China", listOf("china","cn","chinese","flag"), EmojiCategory.FLAGS),
        EmojiItem("🇧🇷","flag: Brazil", listOf("brazil","br","flag"), EmojiCategory.FLAGS),
        EmojiItem("🇵🇰","flag: Pakistan", listOf("pakistan","pk","flag"), EmojiCategory.FLAGS),
        EmojiItem("🇸🇦","flag: Saudi Arabia", listOf("saudi","sa","flag"), EmojiCategory.FLAGS),
        EmojiItem("🇦🇪","flag: United Arab Emirates", listOf("uae","dubai","flag"), EmojiCategory.FLAGS),
        EmojiItem("🇷🇺","flag: Russia", listOf("russia","ru","flag"), EmojiCategory.FLAGS),
        EmojiItem("🇪🇸","flag: Spain", listOf("spain","es","spanish","flag"), EmojiCategory.FLAGS),
        EmojiItem("🇮🇩","flag: Indonesia", listOf("indonesia","id","flag"), EmojiCategory.FLAGS),
        EmojiItem("🇹🇷","flag: Turkey", listOf("turkey","tr","flag"), EmojiCategory.FLAGS),
        EmojiItem("🇰🇷","flag: South Korea", listOf("korea","kr","south korea","flag"), EmojiCategory.FLAGS),
        EmojiItem("🇳🇬","flag: Nigeria", listOf("nigeria","ng","flag"), EmojiCategory.FLAGS)
    )
}
